POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjY1MDZiZmFmZWIyZDdlMmRmMDRhNDZlNSIsImlkIjoiNjUwNmJmYWZlYjJkN2UyZGYwNGE0NmU1IiwiaWF0IjoxNjk0OTQ2MDY3LCJleHAiOjE2OTQ5NDk2Njd9.qzDoqFMybrnALpgG_96rVHH7sUbaoUnXR-pL26n2kAg

{
  "title": "Another one testing 12",
  "author": "Author",
  "url": "http://exemple.com",
  "likes": 1
}
