POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjY1MDZiZmFmZWIyZDdlMmRmMDRhNDZlNSIsImlkIjoiNjUwNmJmYWZlYjJkN2UyZGYwNGE0NmU1IiwiaWF0IjoxNjk0OTQ5MDY2LCJleHAiOjE2OTQ5NTI2NjZ9.JxPYTSek0vT_gwF7-XcutJsn-c02LsgD8XrdoBMs2XE

{
  "title": "Middleware test",
  "author": "Author",
  "url": "http://exemple.com",
  "likes": 1
}
