POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2HybmFtZSI6IjY1MDZiZmFmZWIyZDdlMmRmMDRhNDZlNSIsImlkIjoiNjUwNmJmYWZlYjJkN2UyZGYwNGE0NmU1IiwiaWF0IjoxNjk0OTUyODU2LCJleHAiOjE2OTQ5NTY0NTZ9.6RoCO5fdpMcdHcfS-5R5kSUt2s7yn-ydQ_6543T2lyo

{
  "title": "Middleware test",
  "author": "Author",
  "url": "http://exemple.com",
  "likes": 1
}
